# Generated by Django 5.2.8 on 2025-11-29 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('IT', 'IT / Security'), ('SAFETY', 'Health & Safety'), ('HR', 'HR / Conduct'), ('DATA', 'Data Protection'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('CRIT', 'Critical')], default='MED', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INPR', 'In progress'), ('RES', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
